#!/usr/bin/env bash

ROOT_DIR="$(dirname $(dirname $(dirname $(realpath -L -P ${BASH_SOURCE[0]}))))"

echo $ROOT_DIR

cp --dereference /etc/resolv.conf /mnt/gentoo/etc/

mount --types proc /proc /mnt/gentoo/proc
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev

chroot /mnt/gentoo /bin/bash
